export const FunctionType =  {
    BINARY_MINUS: 0,
    BINARY_PLUS: 1,
    BINARY_MULTIPLY: 2,
    BINARY_DIVISION: 3,
    BINARY_EQUAL: 4,
    BINARY_NOT_EQUAL: 5,
    BINARY_GREATER_THAN: 6,
    BINARY_GREATER_THAN_OR_EQUAL: 7,
    BINARY_LESS_THAN: 8,
    BINARY_LESS_THAN_OR_EQUAL: 9,
    TERNARY_CONDITIONAL: 10,
}